### ISSUE TITLE
'debug' field needs to be set whenever any api doc is created

### ISSUE THREAD

**Issue by JaikrishnaTS** [GRAPLE/GWS#12]
The API manager doesn't set it by default, but ems checks the debug status every time. 

EMS fails if the key is not found. 

Fix: handle by adding 'debug':False in API manager always. 

Also try to safely handle stuff in EMS.

**Comment by vahid-dan** [comment]
Fixed in v3.1.0
https://github.com/GRAPLE/GWS/commit/7880c03f0ae3f37f5360e9c1440ac1544cb3871e
